### ISSUE TITLE
Missing icons

### ISSUE THREAD

**Issue by zoobporsor** [TheFrankyDoll/win10-style-waybar#2]
What would cause missing icons? I dont have a volume icon, or a start menu icon like the example picture shows

**Comment by TheFrankyDoll** [comment]
Since all icons are just font glyphs, you may not have a [NerdFont](https://www.nerdfonts.com) installed. In the default style.css it tries to draw OS button using `JetBrainsMono Nerd Font`, however waybar will usually fallback to any nerdfont available on your system.

Closing this because this is not my config issue.
